### ISSUE TITLE
output variable is not assigned properly in converted nnef from tensorflow.

### ISSUE THREAD

**Issue by lcskrishna** [KhronosGroup/NNEF-Tools#20] opened 2018-04-24 00:34 UTC
Hi,
I tried conversions from TF=> NNEF. After the conversions, I got the nnef structure.

It seems to be like the output variable (output) is not created in the structure. 
Here is the sample NNEF graph from [VGG16 model](http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz) 

Here is the graph.nnef file
```
version 1.0

graph network( input ) -> ( output )
{
        input = external(shape = [1, 3, 224, 224]);
        kernel1 = variable(shape = [64, 3, 3, 3], label = 'vgg_16/conv1/conv1_1/kernel');
        bias1 = variable(shape = [1, 64], label = 'vgg_16/conv1/conv1_1/bias');
        conv1 = conv(input, kernel1, bias1, padding = [], border = 'constant', stride = [1, 1], dilation = [1, 1]);

.........

        relu15 = relu(conv15);
        kernel16 = variable(shape = [1000, 4096, 1, 1], label = 'vgg_16/fc8/kernel');
        bias16 = variable(shape = [1, 1000], label = 'vgg_16/fc8/bias');
        conv16 = conv(relu15, kernel16, bias16, padding = [], border = 'constant', stride = [1, 1], dilation = [1, 1]);
}

```

From the above, nnef graph mentions (input => output) and the final layer assigned is conv16.

Chaitanya.

**Comment by gyenesvi** [comment] 2018-04-24 12:18
The problem is probably that the VGG network ends with a `squeeze` operation, which the current provisional version of NNEF does not support (actually, in case of the VGG network, it is not even required). For this reason, the exporter skips the squeeze operation, resulting in this bug. However, You can fix the export by setting `spatial_squeeze = False` in the main VGG call.

The final version of NNEF will support squeeze and it will be exported properly.

**Comment by lcskrishna** [comment] 2018-04-24 23:52
@gyenesvi 
Thanks for the info.. !!!

Also, a quick question on the checkpoint model files being used for conversion.
I tried to convert .ckpt files (old version) to NNEF model and most of them passed. 
But, when I try to save the models with new version of tensorflow it saves into three files (.ckpt-meta, .ckpt-data and .ckpt-index).

but when I try to use the latest .ckpt files (.ckpt-data) I got the following error:

```
    reader = tf.contrib.framework.load_checkpoint(checkpoint) if checkpoint is not None else None
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/framework/checkpoint_utils.py", line 63, in load_checkpoint
    return train.NewCheckpointReader(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file imagenet_vgg19.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```

Is the new format not supported yet? Or am I using it in the wrong way?

Thanks.

**Comment by gyenesvi** [comment] 2018-05-22 13:17
Sorry for not responding earlier. It seems that it works fine on our side. I guess one problem may be that you don't have to supply the whole file name, but only "imagenet_vgg19.ckpt" even in the later versions when the actual file has different names. Have you tried it that way?

**Comment by gyenesvi** [comment] 2018-05-31 09:17
I close this as the original issue has been fixed.

**Closed by gyenesvi** 2018-05-31 09:17 UTC
